app:
  build: .
  volumes:
   - ./app:/app
  links:
   - neo4j
  ports:
   - "13000:3000"
  entrypoint: node app.js

neo4j:
  image: neo4j:3.0
  ports:
   - "17474:7474"
  volumes:
   - ./db/dbms:/data/dbms

console:
  build: .
  volumes:
   - ./app:/app
  links:
   - neo4j
  entrypoint: bash
